Iter9
MAGeorg/shortener pull request #12
Opened 2024-04-04 08:33 UTC by MAGeorg

2024-04-05 14:42 UTC, arttet requested changes

2024-04-05 14:42 UTC, arttet commented on cmd/shortener/main.go
> +	if cfg.StorageFileName != "" {
CHANGE REQUEST: please simplify it

2024-04-05 14:42 UTC, arttet commented on internal/config/config.go
> +	if a := os.Getenv("SERVER_ADDRESS"); a != "" {
CHANGE REQUEST: this is a magic name

2024-04-05 14:42 UTC, arttet commented on internal/handlers/handlers.go
> +		err := h.a.Producer.WriteEvent(&models.Event{ID: h.a.LastID, HashURL: hash, URL: string(urlStr)})
CHANGE REQUEST: we shouldn't do it here

2024-04-05 14:42 UTC, arttet commented on internal/logger/logger.go
> +var Sugar zap.SugaredLogger
CHANGE REQUEST: please don't use global variables

2024-04-05 14:42 UTC, arttet commented on internal/middleware/gzip.go
> +func MiddlewareGzip(h http.HandlerFunc) http.HandlerFunc {
```suggestion
func GzipMiddleware(h http.HandlerFunc) http.HandlerFunc {
```

2024-04-05 14:42 UTC, arttet commented on internal/models/models.go
> +type AnswerHashURL struct {
```suggestion
type ResponseHashURL struct {
```

2024-04-08 19:53 UTC, MAGeorg commented
golangci-lint и covarege добавлен в первом sprint review
могу ли я дополнительное задание в виде swagger, Dependabot в процессе выполнения sprint 3, если вдруг не успею до окончания приема 2ого sprit?

2024-04-11 14:54 UTC, arttet approved these changes

2024-04-11 14:54 UTC, arttet commented on internal/core/stor_handler.go
> +func CreateShotURL(i InputValueForWriteFile) (string, error) {
```suggestion
func CreateShotURL(i *InputValueForWriteFile) (string, error) {
```

2024-04-11 14:54 UTC, arttet commented on internal/core/stor_handler.go
> +	if *i.LastID != -1 {
This is not an efficient solution.

2024-04-12 06:17 UTC, merged