Iter5
MAGeorg/shortener pull request #5
Opened 2024-03-14 06:29 UTC by MAGeorg

2024-03-14 14:20 UTC, arttet requested changes
Please integrate the following actions in CI:
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-14 14:20 UTC, arttet commented on internal/config/config.go
> +var Conf Config
CHANGE REQUEST: please avoid global variables

2024-03-14 14:20 UTC, arttet commented on internal/handlers/handlers.go
> +var savedURL = map[uint32]string{}
CHANGE REQUEST: please create a new layer for it

2024-03-14 14:20 UTC, arttet commented on internal/handlers/handlers.go
> +func generateURL(s string) uint32 {
CHANGE REQUEST: avoid business logic inside controllers

2024-03-14 14:20 UTC, arttet commented on internal/handlers/handlers.go
> +	s := r.URL.String()[1:]
CHANGE REQUEST: this is an unsafe operation

2024-03-18 12:49 UTC, MAGeorg commented on internal/config/config.go
> +var Conf Config
я довольно долго думал, не совсем понятно как в таком случае, пробрасывать данные из config - BaseAddress в Handler
предлагаете мне переписать стандартный HandleFunc?
```
type HandlerFunc func(ResponseWriter, *Request)

func (f HandlerFunc) ServeHTTP(w ResponseWriter, r *Request) {
	f(w, r)
}
```

2024-03-19 16:38 UTC, arttet requested changes

2024-03-19 16:38 UTC, arttet commented on internal/appcontext/appcontext.go
> +type AppContext struct {
SUGGESTION: it would like better if you rename it like `AppData`

2024-03-19 16:38 UTC, arttet commented on internal/handlers/handlers.go
> +func (h AppHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
CHANGE REQUEST: please remove it

2024-03-19 16:38 UTC, arttet commented on internal/handlers/handlers.go
> +func CreateHashURL(ctx *appcontext.AppContext, w http.ResponseWriter, r *http.Request) {
```suggestion
func (h *AppHandler) CreateHashURL(w http.ResponseWriter, r *http.Request) {
```

2024-03-19 16:38 UTC, arttet commented on internal/handlers/server.go
> +	r.Method("POST", "/", AppHandler{ctx, CreateHashURL})
```suggestion
	r.Method("POST", "/", h.CreateHashURL)
```

2024-03-19 16:38 UTC, arttet commented on internal/handlers/server.go
> +	r.Method("GET", "/{id}", AppHandler{ctx, GetOriginURL})
```suggestion
	r.Method("GET", "/{id}", h.GetOriginURL)
```

2024-03-19 16:38 UTC, arttet commented on internal/handlers/server.go
> +		panic(err)
CHANGE REQUEST: please return the error

2024-03-19 18:38 UTC, MAGeorg commented on internal/handlers/handlers.go
> +func (h AppHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
без ServeHTTP не будет реализации [Handler](https://pkg.go.dev/net/http#Handler)

2024-03-19 18:41 UTC, MAGeorg commented on internal/handlers/server.go
> +	r.Method("POST", "/", AppHandler{ctx, CreateHashURL})
не скомпилится (причина в комментарии к CHANGE REQUEST)

2024-03-21 06:45 UTC, arttet commented on internal/handlers/server.go
> +	r.Method("POST", "/", AppHandler{ctx, CreateHashURL})
This is the example how you need to change it

2024-03-22 07:50 UTC, arttet approved these changes

2024-03-22 13:10 UTC, merged